In [2]:
import torch
import pandas as pd
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import torchvision
import pathlib

from torchvision import transforms, datasets
from torchmetrics.classification import MulticlassAccuracy
# from torchvision import dataset
from torch.utils.data import DataLoader

In [3]:
path = pathlib.Path.home() / "Downloads/csiro-biomass"

train = pd.read_csv(path / "train.csv")
test = pd.read_csv(path / "test.csv")

In [4]:
train.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750

In [5]:
test.head()

                    sample_id             image_path   target_name
0  ID1001187975__Dry_Clover_g  test/ID1001187975.jpg  Dry_Clover_g
1    ID1001187975__Dry_Dead_g  test/ID1001187975.jpg    Dry_Dead_g
2   ID1001187975__Dry_Green_g  test/ID1001187975.jpg   Dry_Green_g
3   ID1001187975__Dry_Total_g  test/ID1001187975.jpg   Dry_Total_g
4         ID1001187975__GDM_g  test/ID1001187975.jpg         GDM_g

In [6]:
train['target_name']

0       Dry_Clover_g
1         Dry_Dead_g
2        Dry_Green_g
3        Dry_Total_g
4              GDM_g
            ...
1780    Dry_Clover_g
1781      Dry_Dead_g
1782     Dry_Green_g
1783     Dry_Total_g
1784           GDM_g
Name: target_name, Length: 1785, dtype: object

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1785 entries, 0 to 1784
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sample_id      1785 non-null   object
 1   image_path     1785 non-null   object
 2   Sampling_Date  1785 non-null   object
 3   State          1785 non-null   object
 4   Species        1785 non-null   object
 5   Pre_GSHH_NDVI  1785 non-null   float64
 6   Height_Ave_cm  1785 non-null   float64
 7   target_name    1785 non-null   object
 8   target         1785 non-null   float64
dtypes: float64(3), object(6)
memory usage: 125.6+ KB

In [8]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sample_id    5 non-null      object
 1   image_path   5 non-null      object
 2   target_name  5 non-null      object
dtypes: object(3)
memory usage: 252.0+ bytes

In [9]:
train.describe()

       Pre_GSHH_NDVI  Height_Ave_cm       target
count    1785.000000    1785.000000  1785.000000
mean        0.657423       7.595985    24.782295
std         0.151972      10.273725    25.823738
min         0.160000       1.000000     0.000000
25%         0.560000       3.000000     4.818200
50%         0.690000       4.000000    18.200000
75%         0.770000       7.000000    35.940600
max         0.910000      70.000000   185.700000

In [10]:
# train_loader = DataLoader()

label = {label: idx for idx, label in enumerate(train["target_name"].unique())}
label

{'Dry_Clover_g': 0,
 'Dry_Dead_g': 1,
 'Dry_Green_g': 2,
 'Dry_Total_g': 3,
 'GDM_g': 4}

In [11]:
# label[train["target_name"]]

# lst = []

# for idx, target in enumerate(train["target_name"]):
#     ...

In [12]:
# path = pathlib.Path.home() / "Downloads/csiro-biomass" / "train/ID1463690813.jpg"

# image = Image.open(path).convert("RGB")
# path.name
# image

In [13]:
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from PIL import Image
from torchvision import transforms
from pathlib import Path

class BiomassDataset(Dataset):
    def __init__(self, csv_file, transform=None):
        super().__init__()

        self.annotation = pd.read_csv(csv_file)
        self.transform = transform
        self.base_path = Path.home() / "Downloads/csiro-biomass"

        self.label_to_idx = {label: idx for idx, label in enumerate(self.annotation["target_name"].unique())}

    def __len__(self):
        return len(self.annotation)

    def __getitem__(self, idx):
        row = self.annotation.iloc[idx]
        image_path = self.base_path / row["image_path"]
        label_name = row["target_name"]
        label = self.label_to_idx[label_name]

        image = Image.open(image_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, torch.tensor(label, dtype=torch.long)

In [14]:
transform = transforms.Compose(
    [
        transforms.Resize((224, 224)),
        transforms.ToTensor()
    ]
)

dataset = BiomassDataset(csv_file = path / "train.csv", transform = transform)
data_loader = DataLoader(dataset, batch_size = 32, shuffle = True)
image, label = next(iter(data_loader))

image.shape

torch.Size([32, 3, 224, 224])

In [15]:
label

tensor([0, 3, 3, 2, 3, 2, 3, 2, 2, 3, 1, 4, 4, 1, 3, 2, 0, 4, 2, 2, 0, 2, 4, 2,
        3, 2, 2, 1, 3, 1, 1, 4])

In [17]:
dataset.classes

AttributeError: 'BiomassDataset' object has no attribute 'classes'

In [52]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

_traindata = datasets.ImageFolder(root = path / "train", transform = transforms)
train_loader = DataLoader(
    _traindata,
    shuffle = True,
    batchsize = 10
)

_testdata = datasets.ImageFolder(root = path / "test", transform = transforms)
test_loader = DataLoader(
    _testdata,
    shuffle = False,
    batch_size = 10
)

FileNotFoundError: Couldn't find any class folder in /Users/kuroyami/Downloads/csiro-biomass/train.