In [8]:
import torch
import torchvision
import pandas as pd
import matplotlib.pyplot as plt
import pathlib

from sklearn.preprocessing import LabelEncoder

In [5]:
root = pathlib.Path(pathlib.Path.home() / "Downloads" / "csiro-biomass")

In [6]:
train_data = pd.read_csv(root / "train.csv")

In [7]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750

In [10]:
sampling_date = pd.to_datetime(train_data["Sampling_Date"])

In [15]:
train_data["Sampling_Year"] = sampling_date.dt.year
train_data["Sampling_Month"] = sampling_date.dt.month
train_data["Sampling_Day"] = sampling_date.dt.day

In [16]:
train_data

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1780,ID983582017__Dry_Clover_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Clover_g,0.0000,2015,9,1
1781,ID983582017__Dry_Dead_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Dead_g,0.0000,2015,9,1
1782,ID983582017__Dry_Green_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Green_g,40.9400,2015,9,1
1783,ID983582017__Dry_Total_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Total_g,40.9400,2015,9,1
1784,ID983582017__GDM_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,GDM_g,40.9400,2015,9,1

In [19]:
state_encoder = LabelEncoder()
species_encoder = LabelEncoder()

In [21]:
train_data["State_encoded"] = state_encoder.fit_transform(train_data["State"])
train_data["Species_encoded"] = species_encoder.fit_transform(train_data["Species"])

In [22]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day,State_encoded,Species_encoded
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4,1,11
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4,1,11
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4,1,11
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4,1,11
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4,1,11

In [25]:
train_data["NDVI_height"] = train_data["Pre_GSHH_NDVI"] ** train_data["Height_Ave_cm"]
train_data["NDVI_sq"] = train_data["Pre_GSHH_NDVI"] ** 2
train_data["Height_sq"] = train_data["Height_Ave_cm"] ** 2

In [26]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day,State_encoded,Species_encoded,NDVI_height,NDVI_sq,Height_sq
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4,1,11,0.107437,0.3844,21.778089
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4,1,11,0.107437,0.3844,21.778089
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4,1,11,0.107437,0.3844,21.778089
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4,1,11,0.107437,0.3844,21.778089
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4,1,11,0.107437,0.3844,21.778089

In [27]:
train_data["mean_target_per_species"] = train_data.groupby("Species")["target"].transform("mean")
train_data["mean_target_per_state"] = train_data.groupby("State")["target"].transform("mean")

In [28]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day,State_encoded,Species_encoded,NDVI_height,NDVI_sq,Height_sq,mean_target_per_species,mean_target_per_state
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785