In [1]:
import torch
import torchvision
import pandas as pd
import matplotlib.pyplot as plt
import pathlib

from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader

In [2]:
root = pathlib.Path(pathlib.Path.home() / "Downloads" / "csiro-biomass")

In [3]:
train_data = pd.read_csv(root / "train.csv")

In [4]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750

In [5]:
sampling_date = pd.to_datetime(train_data["Sampling_Date"])

In [6]:
train_data["Sampling_Year"] = sampling_date.dt.year
train_data["Sampling_Month"] = sampling_date.dt.month
train_data["Sampling_Day"] = sampling_date.dt.day

In [7]:
train_data

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1780,ID983582017__Dry_Clover_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Clover_g,0.0000,2015,9,1
1781,ID983582017__Dry_Dead_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Dead_g,0.0000,2015,9,1
1782,ID983582017__Dry_Green_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Green_g,40.9400,2015,9,1
1783,ID983582017__Dry_Total_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,Dry_Total_g,40.9400,2015,9,1
1784,ID983582017__GDM_g,train/ID983582017.jpg,2015/9/1,WA,Ryegrass,0.64,9.0000,GDM_g,40.9400,2015,9,1

In [8]:
state_encoder = LabelEncoder()
species_encoder = LabelEncoder()

In [9]:
train_data["State_encoded"] = state_encoder.fit_transform(train_data["State"])
train_data["Species_encoded"] = species_encoder.fit_transform(train_data["Species"])

In [10]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day,State_encoded,Species_encoded
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4,1,11
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4,1,11
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4,1,11
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4,1,11
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4,1,11

In [11]:
train_data["NDVI_height"] = train_data["Pre_GSHH_NDVI"] ** train_data["Height_Ave_cm"]
train_data["NDVI_sq"] = train_data["Pre_GSHH_NDVI"] ** 2
train_data["Height_sq"] = train_data["Height_Ave_cm"] ** 2

In [12]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day,State_encoded,Species_encoded,NDVI_height,NDVI_sq,Height_sq
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4,1,11,0.107437,0.3844,21.778089
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4,1,11,0.107437,0.3844,21.778089
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4,1,11,0.107437,0.3844,21.778089
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4,1,11,0.107437,0.3844,21.778089
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4,1,11,0.107437,0.3844,21.778089

In [13]:
train_data["mean_target_per_species"] = train_data.groupby("Species")["target"].transform("mean")
train_data["mean_target_per_state"] = train_data.groupby("State")["target"].transform("mean")

In [14]:
train_data.head()

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target,Sampling_Year,Sampling_Month,Sampling_Day,State_encoded,Species_encoded,NDVI_height,NDVI_sq,Height_sq,mean_target_per_species,mean_target_per_state
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750,2015,9,4,1,11,0.107437,0.3844,21.778089,20.753122,19.032785

In [25]:
import torch
from torch.utils.data import Dataset
import pandas as pd
from PIL import Image
import pathlib

class BiomassDataset(Dataset):
    def __init__(self, csv_path, root, transform=None, include_tabular=True):
        super().__init__()

        self.annotation = pd.read_csv(csv_path)
        self.root = pathlib.Path(root)
        self.transform = transform
        self.include_tabular = include_tabular

        self.grouped = (
            self.annotation
            .pivot_table(index=[
                "image_path", "Sampling_Date", "State", "Species",
                "Pre_GSHH_NDVI", "Height_Ave_cm"
            ], columns="target_name", values="target")
            .reset_index()
        )

        self.target_cols = [
            "Dry_Clover_g",
            "Dry_Dead_g",
            "Dry_Green_g",
            "Dry_Total_g",
            "GDM_g"
        ]

        if self.include_tabular:
            self._prepare_tabular_features()

    def _prepare_tabular_features(self):
        """Create engineered numeric tabular features."""

        df = self.grouped

        df["Sampling_Date"] = pd.to_datetime(df["Sampling_Date"], errors="coerce")
        df["month"] = df["Sampling_Date"].dt.month.fillna(0)
        df["dayofyear"] = df["Sampling_Date"].dt.dayofyear.fillna(0)

        df["State_enc"] = df["State"].astype("category").cat.codes
        df["Species_enc"] = df["Species"].astype("category").cat.codes

        df["NDVI_height"] = df["Pre_GSHH_NDVI"] * df["Height_Ave_cm"]
        df["NDVI_sq"] = df["Pre_GSHH_NDVI"] ** 2
        df["height_sq"] = df["Height_Ave_cm"] ** 2

        self.tabular_cols = [
            "Pre_GSHH_NDVI", "Height_Ave_cm", "month", "dayofyear",
            "State_enc", "Species_enc", "NDVI_height", "NDVI_sq", "height_sq"
        ]

        self.grouped = df

    def __len__(self):
        return len(self.grouped)

    def __getitem__(self, idx):
        row = self.grouped.iloc[idx]

        img_path = self.root / row["image_path"]
        image = Image.open(img_path).convert("RGB")
        if self.transform:
            image = self.transform(image)

        target = pd.to_numeric(row[self.target_cols], errors="coerce").astype("float32")
        target = torch.tensor(target.values, dtype=torch.float32)

        if self.include_tabular:
            tabular_data = pd.to_numeric(row[self.tabular_cols], errors="coerce").astype("float32")
            tabular_data = torch.tensor(tabular_data.values, dtype=torch.float32)
            return image, tabular_data, target
        else:
            return image, target

In [26]:
class BiomassTestDataset(Dataset):
    def __init__(self, csv_path, root, transform = None):
        super(BiomassTestDataset, self).__init__()

        self.annonation = pd.read_csv(csv_path)
        self.root = pathlib.Path(root)
        self.transform = transform

    def __len__(self):
        return len(self.annonation)

    def __getitem__(self, idx):
        rows = self.annonation.iloc[idx]
        
        img_path = self.root / rows["image_path"]
        image = Image.open(img_path).convert("RGB")

        # target = pd.to_numeric(rows["target_name"], errors = "coerce").astype("float32")
        # target = torch.tensor(target).type(torch.float32)

        target = rows["target_name"]
        sample_id = rows["sample_id"]

        # target = torch.tensor(rows["target_name"], dtype=torch.float32)

        if self.transform:
            image = self.transform(image)

        return image, target, sample_id

In [27]:
from torchvision import transforms

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(25),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.ToTensor(),
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

In [28]:
train_dataset = BiomassDataset(csv_path = root / "train.csv", root = root, transform = train_transform)
test_dataset = BiomassTestDataset(csv_path = root / "test.csv", root = root, transform = test_transform)

In [30]:
train_size = int(0.8 * len(train_dataset))
val_size = len(train_dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(train_dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

image, tabular_data, target = next(iter(train_loader))
image.shape, target.shape, tabular_data.shape

(torch.Size([32, 3, 224, 224]), torch.Size([32, 5]), torch.Size([32, 9]))

In [ ]:
train_dataloader = torch.data.utils.DataLoader()

In [81]:
import torch
import torch.nn as nn
import torchvision

class CsiroHybridModel(nn.Module):
    def __init__(self, num_tabular_features: int = 9, hidden_units: int = 64, out_features: int = 5):
        super().__init__()

        self.cnn = torchvision.models.resnet18(weights=torchvision.models.ResNet18_Weights.IMAGENET1K_V1)
        in_features = self.cnn.fc.in_features
        self.cnn.fc = nn.Identity() 

        self.tabular = nn.Sequential(
            nn.Linear(num_tabular_features, hidden_units),
            nn.BatchNorm1d(hidden_units),
            nn.ReLU(),
            nn.Dropout(0.25),
            nn.Linear(hidden_units, 32),
            nn.ReLU()
        )

        self.fc = nn.Sequential(
            nn.Linear(in_features + 32, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, out_features)
        )

    def forward(self, img, tabular):
        img_feat = self.cnn(img)         # [B, 512]
        tab_feat = self.tabular(tabular) # [B, 32]
        x = torch.cat([img_feat, tab_feat], dim=1)
        return self.fc(x)

In [82]:
device = "mps" if torch.mps.is_available() else "cpu"
torch.manual_seed(42)

In [83]:
model = CsiroHybridModel().to(device)
# model

In [84]:
def r2_score_fn(y_true, y_pred):
    ss_res = torch.sum((y_true - y_pred) ** 2, dim=0)
    ss_tot = torch.sum((y_true - torch.mean(y_true, dim=0)) ** 2, dim=0)
    r2 = 1 - ss_res / ss_tot
    return r2

def weighted_r2(y_true, y_pred):
    weights = torch.tensor([0.1, 0.1, 0.1, 0.5, 0.2], device=y_true.device)
    r2 = r2_score_fn(y_true, y_pred)
    final = torch.sum(weights * r2)
    return r2, final

In [85]:
def train_model(model, criterion, optimizer, scheduler, device, dataset, r2score):
    model.train()
    r2score.reset()
    total_loss = 0.0

    for img, tab, target in dataset:
        img, tab, target = img.to(device), tab.to(device), target.to(device)

        optimizer.zero_grad()
        pred = model(img, tab)
        loss = criterion(pred, target)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=2.0)
        optimizer.step()

        total_loss += loss.item()
        r2score.update(pred, target)

    if scheduler:
        scheduler.step()

    avg_loss = total_loss / len(dataset)
    avg_r2 = r2score.compute().item()
    return avg_loss, avg_r2

In [86]:
def eval_model(model, criterion, dataset, device):
    model.eval()
    total_loss = 0.0
    y_true, y_pred = [], []

    with torch.inference_mode():
        for img, tab, target in dataset:
            img, tab, target = img.to(device), tab.to(device), target.to(device)
            pred = model(img, tab)
            loss = criterion(pred, target)
            total_loss += loss.item()

            y_true.append(target)
            y_pred.append(pred)

    y_true = torch.cat(y_true)
    y_pred = torch.cat(y_pred)

    r2, weighted = weighted_r2(y_true, y_pred)
    return total_loss / len(dataset), r2.cpu(), weighted.cpu().item()

In [87]:
from torchmetrics.regression import R2Score
from tqdm.auto import tqdm

criterion = torch.nn.SmoothL1Loss() 
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)

r2score = R2Score().to(device)

In [ ]:
best_r2 = -float("inf")
patience, trigger = 5, 0  

for epoch in tqdm(range(50), desc="Training"):
    train_loss, train_r2 = train_model(model, criterion, optimizer, scheduler, device, train_loader, r2score)
    val_loss, val_r2s, val_weighted_r2 = eval_model(model, criterion, val_loader, device)

    if epoch % (0.1 * 50) == 0:
        print(f"[Epoch {epoch+1}] Train Loss: {train_loss:.4f}, R²: {train_r2:.4f} | Val Loss: {val_loss:.4f}, Weighted R²: {val_weighted_r2:.4f}")
    
        if val_weighted_r2 > best_r2:
            best_r2 = val_weighted_r2
            torch.save(model.state_dict(), "best_model.pth")
            print("✅ Saved new best model")

Training:   2%|▋                                 | 1/50 [00:08<07:18,  8.96s/it]

[Epoch 1] Train Loss: 6.3321, R²: 0.6418 | Val Loss: 9.1360, Weighted R²: 0.3952
✅ Saved new best model

Training:  12%|████                              | 6/50 [00:52<06:26,  8.78s/it]

[Epoch 6] Train Loss: 7.9191, R²: 0.5938 | Val Loss: 9.4159, Weighted R²: 0.3657

Training:  22%|███████▎                         | 11/50 [01:37<05:45,  8.85s/it]

[Epoch 11] Train Loss: 6.6681, R²: 0.6639 | Val Loss: 8.4268, Weighted R²: 0.5553
✅ Saved new best model

Training:  32%|██████████▌                      | 16/50 [02:21<04:59,  8.81s/it]

[Epoch 16] Train Loss: 5.3938, R²: 0.7172 | Val Loss: 8.0021, Weighted R²: 0.5557
✅ Saved new best model

Training:  42%|█████████████▊                   | 21/50 [03:06<04:23,  9.09s/it]

[Epoch 21] Train Loss: 5.5427, R²: 0.7376 | Val Loss: 8.5594, Weighted R²: 0.5179

Training:  52%|█████████████████▏               | 26/50 [03:50<03:31,  8.83s/it]

[Epoch 26] Train Loss: 5.7473, R²: 0.7122 | Val Loss: 8.4502, Weighted R²: 0.4913

Training:  62%|████████████████████▍            | 31/50 [04:34<02:47,  8.82s/it]

[Epoch 31] Train Loss: 5.7457, R²: 0.7341 | Val Loss: 8.0336, Weighted R²: 0.5139

Training:  72%|███████████████████████▊         | 36/50 [05:18<02:03,  8.82s/it]

[Epoch 36] Train Loss: 6.5382, R²: 0.7074 | Val Loss: 7.9651, Weighted R²: 0.5022

Training:  82%|███████████████████████████      | 41/50 [06:02<01:19,  8.79s/it]

[Epoch 41] Train Loss: 5.8767, R²: 0.7792 | Val Loss: 7.8635, Weighted R²: 0.4787

Training:  92%|██████████████████████████████▎  | 46/50 [06:46<00:35,  8.77s/it]

[Epoch 46] Train Loss: 5.6969, R²: 0.7637 | Val Loss: 8.4279, Weighted R²: 0.4778

Training:  98%|████████████████████████████████▎| 49/50 [07:12<00:08,  8.81s/it]